version: '3'
services:
  app1:
    image: golang:1.10
    volumes:
      - ~/go/src/github.com/mafuyuk/go-training:/go/src/github.com/mafuyuk/go-training
    working_dir: /go/src/github.com/mafuyuk/go-training/third-party-package/redigo
    command: go run main.go -h localhost -p :8081
    ports:
      - 8081:8080
    depends_on:
      - redis
  app2:
    image: golang:1.10
    volumes:
      - ~/go/src/github.com/mafuyuk/go-training:/go/src/github.com/mafuyuk/go-training
    working_dir: /go/src/github.com/mafuyuk/go-training/third-party-package/redigo
    command: go run main.go -h localhost -p :8082
    ports:
      - 8082:8080
    depends_on:
      - redis
  redis:
    image: redis:4.0
    ports:
      - 6379:6379
