version: '3'
services:
  app:
    image: golang:1.11
    volumes:
      - ~/go/src/github.com/mafuyuk/go-training/third-party-package/jwt-go:/go/src/github.com/mafuyuk/go-training/third-party-package/jwt-go
    working_dir: /go/src/github.com/mafuyuk/go-training/third-party-package/jwt-go
    command: go get -u github.com/oxequa/realize && realize start --server
    ports:
      - 8080:8080